name: chk
on:
  # this won't trigger on merge conflicts.
  pull_request:
    types: [ 'opened', 'edited', 'synchronize']
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run chk againist'
        default: master

jobs:
  chk:
    concurrency:
      group:  ${{ github.workflow }}-${{ github.event_name }}${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      if: ${{ always() }}
      uses: actions/checkout@v3

    - name: check env
      if: ${{ always() }}
      run: |
        set -x
        env | sort

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v ./...
